"""The QR encoder, checked against known-good output rather than itself.

A wrong QR code is not a wrong number on a screen — it is a picture that
looks entirely correct and simply does not scan, discovered by someone
standing in a shop. So this file does not ask "does it still do what it did
last week". It asks "does it match the specification", three separate ways:

  * golden matrices generated by an independent reference implementation
    (the `qrcode` library, which is not a dependency of carraway — the
    vectors were taken once and frozen here),
  * structure the spec fixes regardless of content: finder patterns, timing
    patterns, the dark module, format information and its BCH check,
  * and a partial decode, which pulls the codewords back out of the finished
    grid and confirms the Reed-Solomon syndromes are zero.

That last one is the strongest of the three. It exercises the bitstream, the
error correction, the block interleaving and the module placement together,
and it would fail if any one of them drifted — including in ways a golden
vector taken at one length would not notice.
"""

import hashlib

import pytest

from carraway.ui import qr

# -- golden vectors ------------------------------------------------------
#
# Generated by the `qrcode` reference library at error-correction level M in
# byte mode, one mask pinned per case. Small enough to read as a picture: a
# failing diff shows you the code.

_SMALL: dict[tuple[str, int], tuple[str, ...]] = {
    ("hi", 0): (
        "111111100001101111111",
        "100000101111001000001",
        "101110100011101011101",
        "101110100101001011101",
        "101110101111101011101",
        "100000100101001000001",
        "111111101010101111111",
        "000000000010000000000",
        "101010100110100010010",
        "101100000011010101111",
        "000010111011011101111",
        "001011010101110111010",
        "110100101111011100100",
        "000000001000001000111",
        "111111100100100010011",
        "100000100110001000111",
        "101110101110101010101",
        "101110100111010101010",
        "101110101111011101101",
        "100000100111110111010",
        "111111101101011101111",
    ),
    ("hi", 3): (
        "111111101111101111111",
        "100000101011001000001",
        "101110100011001011101",
        "101110101100101011101",
        "101110100100001011101",
        "100000100010001000001",
        "111111101010101111111",
        "000000001110000000000",
        "101101110110001001011",
        "011101010010100100001",
        "100001111000111110011",
        "001100010010110000010",
        "111010100001010010101",
        "000000001100010100100",
        "111111101100011010100",
        "100000101111111001001",
        "101110100101001001001",
        "101110101000010010010",
        "101110101001010011100",
        "100000100011101011001",
        "111111101101100101000",
    ),
    ("carraway", 2): (
        "111111100101001111111",
        "100000100000101000001",
        "101110101010001011101",
        "101110101000101011101",
        "101110101001101011101",
        "100000101100101000001",
        "111111101010101111111",
        "000000001101100000000",
        "101111100000101111100",
        "001001011100101010101",
        "101011111101010001110",
        "011100001000000001111",
        "010100100011000101000",
        "000000001001111110101",
        "111111100110101000010",
        "100000101111111011100",
        "101110101000100001001",
        "101110101100100010100",
        "101110101111010000000",
        "100000100100000001100",
        "111111101011010100010",
    ),
}

# Larger cases by digest — a full matrix of these would be pages of noise,
# and the small ones above already make failures legible.
_DIGESTS: dict[tuple[str, int], str] = {
    ("6", 0): "204b4645cd33ad37fd0b93482cde773943628852e2780f3ba242557fb70a9b9a",
    ("123456", 5): "9da8ca850ba7bfbd14ba117a2594d960ac3c235a3edf24e83e2596f8d0ca38ae",
    ("HELLO WORLD", 1): "c7636e44b12237cba314e0f334f5e9d0c5236131238e16d645f689ede6d25d57",
    ("x" * 100, 4): "25d8278acc6d7c102b077fb0355a08da99d56b48bee8a5bc1d6a5a4f729e1fce",
    ("y" * 210, 7): "784bc84f73a732a55df3db9b221affc43fb17541c6fa0caaaa5d7ee8e14d83e3",
    ("https://money.aidanjalili.com/pair/9owkb6bmt4f1x88t", 6): (
        "60077a057d01c284f57f3e0ee13d460e63d0dd52242d6f648b74398dcdc14865"
    ),
}


def _rows(grid: list[list[int]]) -> list[str]:
    return ["".join(str(cell) for cell in row) for row in grid]


@pytest.mark.parametrize(("case", "want"), sorted(_SMALL.items()))
def test_matches_reference_matrix(case: tuple[str, int], want: tuple[str, ...]) -> None:
    text, mask = case
    assert _rows(qr.encode(text, mask=mask)) == list(want)


@pytest.mark.parametrize(("case", "digest"), sorted(_DIGESTS.items()))
def test_matches_reference_digest(case: tuple[str, int], digest: str) -> None:
    text, mask = case
    got = "\n".join(_rows(qr.encode(text, mask=mask)))
    assert hashlib.sha256(got.encode()).hexdigest() == digest


def test_digits_use_byte_mode_not_numeric():
    # Carraway implements byte mode only. An all-digit string is a perfectly
    # legal thing to encode that way -- it is just bigger than numeric mode
    # would be. This pins the choice, because a reference implementation
    # left to itself picks numeric here and the two disagree completely.
    assert _rows(qr.encode("6", mask=0)) != _rows(qr.encode("7", mask=0))
    assert len(qr.encode("6", mask=0)) == 21


# -- structure the spec fixes -------------------------------------------

_URL = "https://money.aidanjalili.com/pair/9owkb6bmt4f1x88t"


def test_output_is_square_and_binary():
    for text in ("a", "hi", _URL, "z" * 210):
        grid = qr.encode(text)
        size = len(grid)
        assert (size - 17) % 4 == 0, "not a valid QR size"
        assert all(len(row) == size for row in grid)
        assert {cell for row in grid for cell in row} <= {0, 1}


def test_finder_patterns_in_three_corners():
    finder = [
        "1111111",
        "1000001",
        "1011101",
        "1011101",
        "1011101",
        "1000001",
        "1111111",
    ]
    grid = qr.encode(_URL)
    size = len(grid)
    rows = _rows(grid)
    corners = {
        "top left": [row[:7] for row in rows[:7]],
        "top right": [row[size - 7 :] for row in rows[:7]],
        "bottom left": [row[:7] for row in rows[size - 7 :]],
    }
    for where, block in corners.items():
        assert block == finder, f"{where} finder pattern is wrong"

    # And the fourth corner must *not* have one, or a reader cannot tell
    # which way up the code is.
    assert [row[size - 7 :] for row in rows[size - 7 :]] != finder


def test_timing_patterns_alternate():
    grid = qr.encode(_URL)
    size = len(grid)
    for i in range(8, size - 8):
        want = 1 - (i % 2)
        assert grid[6][i] == want, f"horizontal timing wrong at {i}"
        assert grid[i][6] == want, f"vertical timing wrong at {i}"


def test_dark_module_is_always_set():
    # The one module at (4 * version + 9, 8) that is dark in every valid code.
    for text in ("a", _URL, "z" * 210):
        grid = qr.encode(text)
        version = (len(grid) - 17) // 4
        assert grid[4 * version + 9][8] == 1


def test_quiet_zone_is_the_callers_problem():
    # encode() returns modules only. Rendering adds the margin; if this ever
    # started including one, every caller would draw it twice.
    grid = qr.encode("hi")
    assert grid[0][0] == 1 and grid[0][6] == 1


# -- format information --------------------------------------------------


def _bch_ok(fifteen: int) -> bool:
    """True if the 15 format bits carry a valid BCH(15,5) codeword."""
    residual = fifteen ^ 0x5412  # undo the constant the spec XORs in
    value = residual
    for shift in range(14, 9, -1):
        if value & (1 << shift):
            value ^= 0x537 << (shift - 10)
    return value == 0


def test_format_information_is_written_twice_and_agrees():
    for mask in range(8):
        grid = qr.encode(_URL, mask=mask)
        size = len(grid)

        first = [grid[8][i] for i in range(6)]
        first += [grid[8][7], grid[8][8], grid[7][8]]
        first += [grid[14 - i][8] for i in range(9, 15)]

        second = [grid[size - 1 - i][8] for i in range(7)]
        second += [grid[8][size - 15 + i] for i in range(7, 15)]

        assert first == second, f"the two format copies disagree at mask {mask}"

        bits = int("".join(str(b) for b in first), 2)
        assert _bch_ok(bits), f"format information fails its BCH check at mask {mask}"
        # Bits 13-14 are the error-correction level; 0b00 is level M.
        assert (bits ^ 0x5412) >> 13 == 0b00
        # Bits 10-12 are the mask, and must be the one we asked for.
        assert ((bits ^ 0x5412) >> 10) & 0b111 == mask


def test_mask_is_chosen_not_fixed():
    # If mask selection silently degraded to "always zero" everything would
    # still scan, so nothing else in this file would catch it.
    chosen = set()
    for n in range(1, 60):
        grid = qr.encode(f"https://money.aidanjalili.com/pair/{'a' * n}")
        bits = [grid[8][i] for i in range(6)]
        bits += [grid[8][7], grid[8][8], grid[7][8]]
        bits += [grid[14 - i][8] for i in range(9, 15)]
        value = int("".join(str(b) for b in bits), 2) ^ 0x5412
        chosen.add((value >> 10) & 0b111)
    assert len(chosen) > 1, f"only ever picked mask {chosen}"


# -- a partial decode ----------------------------------------------------


def _unplace(grid: list[list[int]]) -> list[int]:
    """Pull the data codewords back out of a finished grid, in wire order."""
    size = len(grid)
    version = (size - 17) // 4
    _, reserved = qr._blank(size)
    qr._place_fixed([[None] * size for _ in range(size)], reserved, version)

    bits: list[int] = []
    mask = None
    fmt = [grid[8][i] for i in range(6)]
    fmt += [grid[8][7], grid[8][8], grid[7][8]]
    fmt += [grid[14 - i][8] for i in range(9, 15)]
    mask = ((int("".join(str(b) for b in fmt), 2) ^ 0x5412) >> 10) & 0b111

    column = size - 1
    while column > 0:
        if column == 6:  # the vertical timing pattern is skipped entirely
            column -= 1
        upward = ((size - 1 - column) // 2) % 2 == 0
        rows = range(size - 1, -1, -1) if upward else range(size)
        for row in rows:
            for col in (column, column - 1):
                if not reserved[row][col]:
                    cell = grid[row][col]
                    bits.append(cell ^ 1 if qr._mask(row, col, mask) else cell)
        column -= 2
    return [int("".join(str(b) for b in bits[i : i + 8]), 2) for i in range(0, len(bits) - 7, 8)]


def _syndromes_zero(block: list[int], ec_count: int) -> bool:
    """True if this block's Reed-Solomon syndromes all vanish."""
    for i in range(ec_count):
        acc = 0
        x = qr._EXP[i]
        power = 1
        for byte in reversed(block):
            acc ^= qr._mul(byte, power)
            power = qr._mul(power, x)
        if acc != 0:
            return False
    return True


@pytest.mark.parametrize("text", ["a", "hi", _URL, "m" * 90, "q" * 210])
def test_error_correction_checks_out(text: str) -> None:
    """Read the codewords back and confirm the Reed-Solomon maths holds.

    This is the test that covers the whole pipeline at once. It found the
    padding bug (which started 0x11 instead of 0xEC) and would have found
    the interleaving one.
    """
    grid = qr.encode(text)
    version = (len(grid) - 17) // 4
    _, ec_count, blocks1, size1, blocks2, size2 = qr._LEVEL_M[version]

    stream = _unplace(grid)
    groups = [size1] * blocks1 + [size2] * blocks2
    total_blocks = len(groups)

    # Undo the interleave: data first, column by column, then the EC bytes.
    data: list[list[int]] = [[] for _ in groups]
    index = 0
    for position in range(max(groups)):
        for block, length in enumerate(groups):
            if position < length:
                data[block].append(stream[index])
                index += 1
    ec: list[list[int]] = [[] for _ in groups]
    for _ in range(ec_count):
        for block in range(total_blocks):
            ec[block].append(stream[index])
            index += 1

    for block in range(total_blocks):
        assert _syndromes_zero(data[block] + ec[block], ec_count), (
            f"block {block} of {total_blocks} does not satisfy its error correction"
        )
